const prefix = 'organization';

export const GET_ORGANIZATION_REQUEST = `${prefix}/GET_ORGANIZATION_REQUEST`;
export const GET_ORGANIZATION_SUCCESS = `${prefix}/GET_ORGANIZATION_SUCCESS`;
export const GET_ORGANIZATION_FAILURE = `${prefix}/GET_ORGANIZATION_FAILURE`;

export const FETCH_ORGANIZATION_REQUEST = `${prefix}/FETCH_ORGANIZATION_REQUEST`;
export const FETCH_ORGANIZATION_SUCCESS = `${prefix}/FETCH_ORGANIZATION_SUCCESS`;
export const FETCH_ORGANIZATION_FAILURE = `${prefix}/FETCH_ORGANIZATION_FAILURE`;

export const UPDATE_ORGANIZATION_REQUEST = `${prefix}/UPDATE_ORGANIZATION_REQUEST`;
export const UPDATE_ORGANIZATION_SUCCESS = `${prefix}/UPDATE_ORGANIZATION_SUCCESS`;
export const UPDATE_ORGANIZATION_FAILURE = `${prefix}/UPDATE_ORGANIZATION_FAILURE`;

export const GET_ALLIANCES_REQUEST = `${prefix}/GET_ALLIANCES_REQUEST`;
export const GET_ALLIANCES_SUCCESS = `${prefix}/GET_ALLIANCES_SUCCESS`;
export const GET_ALLIANCES_FAILURE = `${prefix}/GET_ALLIANCES_FAILURE`;

export const SEND_PENDING_INVITATION_REQUEST = `${prefix}/SEND_PENDING_INVITATION_REQUEST`;
export const SEND_PENDING_INVITATION_SUCCESS = `${prefix}/SEND_PENDING_INVITATION_SUCCESS`;
export const SEND_PENDING_INVITATION_FAILURE = `${prefix}/SEND_PENDING_INVITATION_FAILURE`;
export const SEND_LEAVE_ALLIANCE_SUCCESS = `${prefix}/SEND_LEAVE_ALLIANCE_SUCCESS`;

export const APPROVE_PENDING_INVITATION_REQUEST = `${prefix}/APPROVE_PENDING_INVITATION_REQUEST`;
export const APPROVE_PENDING_INVITATION_SUCCESS = `${prefix}/APPROVE_PENDING_INVITATION_SUCCESS`;
export const APPROVE_PENDING_INVITATION_FAILURE = `${prefix}/APPROVE_PENDING_INVITATION_FAILURE`;

export const GET_PENDING_INVITATIONS_REQUEST = `${prefix}/GET_PENDING_INVITATIONS_REQUEST`;
export const GET_PENDING_INVITATIONS_SUCCESS = `${prefix}/GET_PENDING_INVITATIONS_SUCCESS`;
export const GET_PENDING_INVITATIONS_FAILURE = `${prefix}/GET_PENDING_INVITATIONS_FAILURE`;

export const GET_ALLIANCE_MEMBERS_REQUEST = `${prefix}/GET_ALLIANCE_MEMBERS_REQUEST`;
export const GET_ALLIANCE_MEMBERS_SUCCESS = `${prefix}/GET_ALLIANCE_MEMBERS_SUCCESS`;
export const GET_ALLIANCE_MEMBERS_FAILURE = `${prefix}/GET_ALLIANCE_MEMBERS_FAILURE`;


export const UPDATE_ALLIANCE_MEMBER = `${prefix}/UPDATE_ALLIANCE_MEMBER`;


export const GET_ALLIANCE_MEMBERS_FOR_RANKING_REQUEST = `${prefix}/GET_ALLIANCE_MEMBERS_FOR_RANKING_REQUEST`;
export const GET_ALLIANCE_MEMBERS_FOR_RANKING_SUCCESS = `${prefix}/GET_ALLIANCE_MEMBERS_FOR_RANKING_SUCCESS`;
export const GET_ALLIANCE_MEMBERS_FOR_RANKING_FAILURE = `${prefix}/GET_ALLIANCE_MEMBERS_FOR_RANKING_FAILURE`;

export const SET_FILTERED_ALLIANCES = `${prefix}/SET_FILTERED_ALLIANCES`;

export const GET_BANDS_REQUEST = `${prefix}/GET_BANDS_REQUEST`;
export const GET_BANDS_SUCCESS = `${prefix}/GET_BANDS_SUCCESS`;
export const GET_BANDS_FAILURE = `${prefix}/GET_BANDS_FAILURE`;
export const SET_FILTERED_BANDS = `${prefix}/SET_FILTERED_BANDS`;